# Generated by Django 4.2.6 on 2023-10-29 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsersActions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choise',
            new_name='Choice',
        ),
    ]
